In [1]:
import numpy as np
from numpy import array

更改ndarray的维度

In [2]:
nd_array = array([[1,2,3], [4,5,6]])
print("reshape: ", nd_array)

new_nd_array = nd_array.reshape((3,2))#改变数组形状
print("reshape: ", new_nd_array)

new_nd_array = new_nd_array.flatten()#将多维数组展开为一维
print("reshape: ", new_nd_array)

reshape:  [[1 2 3]
 [4 5 6]]
reshape:  [[1 2]
 [3 4]
 [5 6]]
reshape:  [1 2 3 4 5 6]


In [3]:
a = array([1, 2, 3, 4])
b = array([10, 20, 30, 40])

合并a和b

In [4]:
print(np.hstack([a, b]))#水平拼接数组
print(np.vstack([a, b]))#垂直拼接数组
print(np.concatenate([a, b], axis = 0))#按指定维度拼接数组

[ 1  2  3  4 10 20 30 40]
[[ 1  2  3  4]
 [10 20 30 40]]
[ 1  2  3  4 10 20 30 40]


In [ ]:
#axis的含义解释
c = np.arange(81).reshape((3,3,3,3))
d = np.array(range(81)).reshape((3,3,3,3))

print("c.shape: ", c.shape)
print("d.shape: ", d.shape)
res = np.concatenate([c, d], axis = 0)
print("res.shape: ", res.shape)

c.shape:  (3, 3, 3, 3)
d.shape:  (3, 3, 3, 3)
res.shape:  (6, 3, 3, 3)


ndarray的条件选择计算

In [7]:
a = array([1, 2, 3, 4])
b = array([10, 20, 30, 40])
c = array([-1, 1, 1, -1])

In [8]:
#a和b的条件拼接
result = np.where(c > 0, a, b)#满足条件则取x，否则取y，所以0位是false，取b的值
print(result)
print("c > 0", c > 0)

[10  2  3 40]
c > 0 [False  True  True False]


In [9]:
conditions = [a < 2, a > 2]
choices = [a * 10, a * 100]
#当a < 2时，返回a * 10
result = np.select(conditions, choices, default = 0)
print(result)

[ 10   0 300 400]


基础数学方法

In [10]:
arr = np.arange(0, 10)

In [13]:
print(arr.min())
print(arr.max())
print(np.median(arr))

#四分点位
Q1 = np.percentile(arr, 25)
print(Q1)
Q1 = np.percentile(arr, 50)
print(Q1)
Q1 = np.percentile(arr, 75)
print(Q1)

print(arr.sum())
print(arr.mean())

print(arr.std())
print(arr.var())


0
9
4.5
2.25
4.5
6.75
45
4.5
2.8722813232690143
8.25


In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [15]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
print(np.dot(arr1, arr2))
print(arr1 @ arr2)
#两种方式等价·点乘而不是叉乘

32
32


In [18]:
print(arr1 ** 2)
print(np.sqrt(arr1))

[1 4 9]
[1.         1.41421356 1.73205081]


In [ ]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat, end = "\n-------------------------\n")
#转置·两种方式等价
print(np.transpose(mat), end = "\n------\n")
print(mat.T)

[[1 2 3]
 [4 5 6]]
-------------------------
[[1 4]
 [2 5]
 [3 6]]
------
[[1 4]
 [2 5]
 [3 6]]


In [23]:
#范数
vec = np.array([3, 4])
print(np.linalg.norm(vec, ord = 1))#L1
print(np.linalg.norm(vec))#L2
print(np.linalg.norm(vec, ord = 3))#L3

7.0
5.0
4.497941445275415


In [24]:
#相关性分析
np.corrcoef(arr1, arr2)#皮尔逊系数矩阵
np.cov(arr1, arr2)#协方差矩阵

array([[1., 1.],
       [1., 1.]])